var classes = [
    {
        "name": "App\\Console\\Kernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "schedule",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "commands",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Console\\Kernel",
            "Illuminate\\Console\\Scheduling\\Schedule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Console\\Kernel"
        ],
        "implements": [],
        "lcom": 2,
        "length": 6,
        "vocabulary": 6,
        "volume": 15.51,
        "difficulty": 0.5,
        "effort": 7.75,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 31.02,
        "number_operators": 1,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 7,
        "loc": 19,
        "lloc": 12,
        "mi": 108.38,
        "mIwoC": 67.99,
        "commentWeight": 40.39,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 1.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 2.5,
        "package": "App\\Console\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Exceptions\\Handler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Exceptions\\Handler"
        ],
        "parents": [
            "Illuminate\\Foundation\\Exceptions\\Handler"
        ],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 9,
        "loc": 19,
        "lloc": 10,
        "mi": 114.36,
        "mIwoC": 70.6,
        "commentWeight": 43.77,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\Exceptions\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\AdminController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "dashboard",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dataPemesanan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "orderDetails",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "kirimWhatsapp",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateOrderStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUkuran",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "simpanInvoice",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "produk",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "tambahProduk",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hapusProduk",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "WorkOrderUpdate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cetakWorkOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 13,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 13,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 39,
        "ccn": 27,
        "ccnMethodMax": 9,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Pemesanan",
            "App\\Models\\Pemesanan",
            "Illuminate\\Support\\Facades\\Http",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pemesanan",
            "Log",
            "App\\Models\\Pemesanan",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Support\\Facades\\File",
            "App\\Models\\DetailPesanan",
            "App\\Models\\Pemesanan",
            "Illuminate\\Http\\Request",
            "App\\Models\\DetailPesanan",
            "App\\Models\\Produk",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Str",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Support\\Facades\\File",
            "App\\Models\\Produk",
            "App\\Models\\Produk",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pemesanan",
            "App\\Models\\Pemesanan",
            "PhpOffice\\PhpSpreadsheet\\IOFactory"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 12,
        "length": 431,
        "vocabulary": 120,
        "volume": 2976.87,
        "difficulty": 11.54,
        "effort": 34340.32,
        "level": 0.09,
        "bugs": 0.99,
        "time": 1908,
        "intelligentContent": 258.06,
        "number_operators": 108,
        "number_operands": 323,
        "number_operators_unique": 8,
        "number_operands_unique": 112,
        "cloc": 21,
        "loc": 204,
        "lloc": 183,
        "mi": 46.53,
        "mIwoC": 22.69,
        "commentWeight": 23.84,
        "kanDefect": 2.47,
        "relativeStructuralComplexity": 2209,
        "relativeDataComplexity": 0.4,
        "relativeSystemComplexity": 2209.4,
        "totalStructuralComplexity": 28717,
        "totalDataComplexity": 5.15,
        "totalSystemComplexity": 28722.15,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\AuthController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "showLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showRegister",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\User",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "App\\Models\\User",
            "App\\Models\\User",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\Models\\User"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 95,
        "vocabulary": 33,
        "volume": 479.22,
        "difficulty": 6.34,
        "effort": 3037.9,
        "level": 0.16,
        "bugs": 0.16,
        "time": 169,
        "intelligentContent": 75.59,
        "number_operators": 24,
        "number_operands": 71,
        "number_operators_unique": 5,
        "number_operands_unique": 28,
        "cloc": 3,
        "loc": 46,
        "lloc": 43,
        "mi": 63.93,
        "mIwoC": 44.66,
        "commentWeight": 19.27,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.71,
        "relativeSystemComplexity": 121.71,
        "totalStructuralComplexity": 484,
        "totalDataComplexity": 2.83,
        "totalSystemComplexity": 486.83,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Routing\\Controller"
        ],
        "parents": [
            "Illuminate\\Routing\\Controller"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.09,
        "afferentCoupling": 7,
        "efferentCoupling": 1,
        "instability": 0.13,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ForgotPasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "showForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleRequest",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\User",
            "Illuminate\\Support\\Facades\\Session",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Support\\Facades\\Session",
            "Str",
            "Illuminate\\Support\\Facades\\Session",
            "Illuminate\\Support\\Facades\\Mail"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 65,
        "vocabulary": 23,
        "volume": 294.03,
        "difficulty": 6.81,
        "effort": 2001.05,
        "level": 0.15,
        "bugs": 0.1,
        "time": 111,
        "intelligentContent": 43.2,
        "number_operators": 16,
        "number_operands": 49,
        "number_operators_unique": 5,
        "number_operands_unique": 18,
        "cloc": 2,
        "loc": 36,
        "lloc": 34,
        "mi": 66.49,
        "mIwoC": 48.64,
        "commentWeight": 17.85,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.39,
        "relativeSystemComplexity": 169.39,
        "totalStructuralComplexity": 338,
        "totalDataComplexity": 0.79,
        "totalSystemComplexity": 338.79,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\LandingController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "home",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "kirimPesan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Produk",
            "App\\Models\\Pemesanan",
            "App\\Models\\User",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pesan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 41,
        "vocabulary": 23,
        "volume": 185.47,
        "difficulty": 1.71,
        "effort": 317.94,
        "level": 0.58,
        "bugs": 0.06,
        "time": 18,
        "intelligentContent": 108.19,
        "number_operators": 5,
        "number_operands": 36,
        "number_operators_unique": 2,
        "number_operands_unique": 21,
        "cloc": 2,
        "loc": 19,
        "lloc": 17,
        "mi": 81.23,
        "mIwoC": 57.14,
        "commentWeight": 24.09,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.28,
        "relativeSystemComplexity": 64.28,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0.56,
        "totalSystemComplexity": 128.56,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\MidtransWebhookController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "kirimWhatsapp",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\Http",
            "Illuminate\\Http\\Request",
            "App\\Models\\Midtrans",
            "App\\Models\\Pemesanan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 95,
        "vocabulary": 44,
        "volume": 518.65,
        "difficulty": 5.37,
        "effort": 2784.31,
        "level": 0.19,
        "bugs": 0.17,
        "time": 155,
        "intelligentContent": 96.61,
        "number_operators": 27,
        "number_operands": 68,
        "number_operators_unique": 6,
        "number_operands_unique": 38,
        "cloc": 7,
        "loc": 43,
        "lloc": 36,
        "mi": 75.36,
        "mIwoC": 46.1,
        "commentWeight": 29.26,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 144.27,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 0.54,
        "totalSystemComplexity": 288.54,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\PemesananController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "showForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "kirimWhatsapp",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buatPesanan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "trackingPesanan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "invoice",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPaymentToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 14,
        "ccnMethodMax": 12,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\Http",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Support\\Str",
            "App\\Models\\Pemesanan",
            "App\\Models\\DetailPesanan",
            "App\\Models\\DetailPesanan",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Pemesanan",
            "App\\Models\\Pemesanan",
            "App\\Models\\DetailPesanan",
            "App\\Models\\Midtrans",
            "App\\Models\\Pemesanan",
            "App\\Models\\DetailPesanan",
            "DB",
            "Midtrans\\Snap",
            "App\\Models\\Midtrans"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 5,
        "length": 364,
        "vocabulary": 117,
        "volume": 2500.81,
        "difficulty": 9.04,
        "effort": 22598.25,
        "level": 0.11,
        "bugs": 0.83,
        "time": 1255,
        "intelligentContent": 276.75,
        "number_operators": 80,
        "number_operands": 284,
        "number_operators_unique": 7,
        "number_operands_unique": 110,
        "cloc": 11,
        "loc": 130,
        "lloc": 119,
        "mi": 50.82,
        "mIwoC": 29.05,
        "commentWeight": 21.78,
        "kanDefect": 1.42,
        "relativeStructuralComplexity": 1369,
        "relativeDataComplexity": 0.21,
        "relativeSystemComplexity": 1369.21,
        "totalStructuralComplexity": 8214,
        "totalDataComplexity": 1.24,
        "totalSystemComplexity": 8215.24,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ProfileController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 9,
        "ccnMethodMax": 9,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Support\\Facades\\File",
            "Illuminate\\Support\\Facades\\File"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 87,
        "vocabulary": 31,
        "volume": 431.02,
        "difficulty": 7.44,
        "effort": 3206.75,
        "level": 0.13,
        "bugs": 0.14,
        "time": 178,
        "intelligentContent": 57.93,
        "number_operators": 25,
        "number_operands": 62,
        "number_operators_unique": 6,
        "number_operands_unique": 25,
        "cloc": 5,
        "loc": 43,
        "lloc": 38,
        "mi": 71.08,
        "mIwoC": 45.88,
        "commentWeight": 25.2,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.28,
        "relativeSystemComplexity": 225.28,
        "totalStructuralComplexity": 450,
        "totalDataComplexity": 0.56,
        "totalSystemComplexity": 450.56,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Kernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Kernel"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Kernel"
        ],
        "implements": [],
        "lcom": 0,
        "length": 16,
        "vocabulary": 16,
        "volume": 64,
        "difficulty": 0.5,
        "effort": 32,
        "level": 2,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 128,
        "number_operators": 1,
        "number_operands": 15,
        "number_operators_unique": 1,
        "number_operands_unique": 15,
        "cloc": 21,
        "loc": 38,
        "lloc": 17,
        "mi": 106.05,
        "mIwoC": 60.38,
        "commentWeight": 45.67,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\AdminSessionMiddleware",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Closure"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 1.5,
        "effort": 34.9,
        "level": 0.67,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 15.51,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 5,
        "loc": 16,
        "lloc": 11,
        "mi": 105.53,
        "mIwoC": 67.45,
        "commentWeight": 38.09,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 3,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\Authenticate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "redirectTo",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Auth\\Middleware\\Authenticate",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "Illuminate\\Auth\\Middleware\\Authenticate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 110.6,
        "mIwoC": 74.41,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\EncryptCookies",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Cookie\\Middleware\\EncryptCookies"
        ],
        "parents": [
            "Illuminate\\Cookie\\Middleware\\EncryptCookies"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\PreventRequestsDuringMaintenance",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\RedirectIfAuthenticated",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\Response",
            "Illuminate\\Http\\Request",
            "Closure",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 7,
        "volume": 42.11,
        "difficulty": 4.13,
        "effort": 173.71,
        "level": 0.24,
        "bugs": 0.01,
        "time": 10,
        "intelligentContent": 10.21,
        "number_operators": 4,
        "number_operands": 11,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 5,
        "loc": 19,
        "lloc": 14,
        "mi": 98.77,
        "mIwoC": 63.09,
        "commentWeight": 35.68,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.67,
        "totalSystemComplexity": 5.67,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\TrimStrings",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings"
        ],
        "implements": [],
        "lcom": 0,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 124.34,
        "mIwoC": 79.88,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\TrustHosts",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "hosts",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Http\\Middleware\\TrustHosts"
        ],
        "parents": [
            "Illuminate\\Http\\Middleware\\TrustHosts"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 5,
        "loc": 13,
        "lloc": 8,
        "mi": 119.04,
        "mIwoC": 78.06,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\TrustProxies",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Http\\Middleware\\TrustProxies"
        ],
        "parents": [
            "Illuminate\\Http\\Middleware\\TrustProxies"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 10,
        "loc": 16,
        "lloc": 6,
        "mi": 218.04,
        "mIwoC": 171,
        "commentWeight": 47.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\ValidateSignature",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Routing\\Middleware\\ValidateSignature"
        ],
        "parents": [
            "Illuminate\\Routing\\Middleware\\ValidateSignature"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\VerifyCsrfToken",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Models\\DetailPesanan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "pesanan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 9,
        "volume": 31.7,
        "difficulty": 0.56,
        "effort": 17.83,
        "level": 1.78,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 56.35,
        "number_operators": 1,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 1,
        "loc": 12,
        "lloc": 11,
        "mi": 88.26,
        "mIwoC": 66.64,
        "commentWeight": 21.62,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\Midtrans",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "pemesanan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 6,
        "volume": 15.51,
        "difficulty": 0.5,
        "effort": 7.75,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 31.02,
        "number_operators": 1,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 10,
        "lloc": 10,
        "mi": 69.71,
        "mIwoC": 69.71,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\Pemesanan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "detail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "midtrans",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "workOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 2,
        "length": 22,
        "vocabulary": 18,
        "volume": 91.74,
        "difficulty": 0.56,
        "effort": 51.27,
        "level": 1.79,
        "bugs": 0.03,
        "time": 3,
        "intelligentContent": 164.16,
        "number_operators": 3,
        "number_operands": 19,
        "number_operators_unique": 1,
        "number_operands_unique": 17,
        "cloc": 1,
        "loc": 22,
        "lloc": 21,
        "mi": 73.5,
        "mIwoC": 57.28,
        "commentWeight": 16.22,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 15,
        "package": "App\\Models\\",
        "pageRank": 0.09,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "App\\Models\\Pesan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 0,
        "length": 7,
        "vocabulary": 6,
        "volume": 18.09,
        "difficulty": 0,
        "effort": 0,
        "level": 1.71,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 31.02,
        "number_operators": 0,
        "number_operands": 7,
        "number_operators_unique": 0,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 71.36,
        "mIwoC": 71.36,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\Produk",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 0,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 7,
        "lloc": 7,
        "mi": 73.97,
        "mIwoC": 73.97,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\Profile",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 8,
        "volume": 24,
        "difficulty": 0.5,
        "effort": 12,
        "level": 2,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 48,
        "number_operators": 1,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 67.48,
        "mIwoC": 67.48,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Models\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "profile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "parents": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0.5,
        "effort": 5.8,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 10,
        "lloc": 10,
        "mi": 70.6,
        "mIwoC": 70.6,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.08,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Models\\WorkOrder",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "pemesanan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 10,
        "volume": 33.22,
        "difficulty": 0.5,
        "effort": 16.61,
        "level": 2,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 66.44,
        "number_operators": 1,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 66.5,
        "mIwoC": 66.5,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AppServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "implements": [],
        "lcom": 2,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 8,
        "loc": 18,
        "lloc": 10,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Providers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AuthServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\AuthServiceProvider"
        ],
        "parents": [
            "Illuminate\\Foundation\\Support\\Providers\\AuthServiceProvider"
        ],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 9,
        "loc": 17,
        "lloc": 8,
        "mi": 216.16,
        "mIwoC": 171,
        "commentWeight": 45.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Providers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\BroadcastServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider",
            "Illuminate\\Support\\Facades\\Broadcast"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "implements": [],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 3,
        "loc": 12,
        "lloc": 9,
        "mi": 205.97,
        "mIwoC": 171,
        "commentWeight": 34.97,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\Providers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\EventServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "shouldDiscoverEvents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\EventServiceProvider"
        ],
        "parents": [
            "Illuminate\\Foundation\\Support\\Providers\\EventServiceProvider"
        ],
        "implements": [],
        "lcom": 2,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 12,
        "loc": 24,
        "lloc": 12,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "App\\Providers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\RouteServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider",
            "Illuminate\\Cache\\RateLimiting\\Limit",
            "Illuminate\\Support\\Facades\\RateLimiter",
            "Illuminate\\Support\\Facades\\Route",
            "Illuminate\\Support\\Facades\\Route"
        ],
        "parents": [
            "Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider"
        ],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 9,
        "volume": 41.21,
        "difficulty": 0.75,
        "effort": 30.91,
        "level": 1.33,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 54.95,
        "number_operators": 1,
        "number_operands": 12,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 10,
        "loc": 25,
        "lloc": 15,
        "mi": 104.29,
        "mIwoC": 62.77,
        "commentWeight": 41.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.09,
        "relativeSystemComplexity": 100.09,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 0.09,
        "totalSystemComplexity": 100.09,
        "package": "App\\Providers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    }
]